export const environment = {
  production: true,
  Web_Api_Url: 'http://151.239.254.82:5000/api/v1/',
  SignUp_Path: 'Authentication/SignUp',
  Login_Path: 'Authentication/Login',
  Chat_Path:'Chat/',
  Users_Path:'User/',
  FileHandler_Path:'File/',
  Download_Path: 'File/Download/',
  Upload_Profile_Picture_Path: 'File/UpdateProfilePicture',
  Delete_Profile_Picture_Path: '/DeleteProfilePicture',
  Upload_Path: '/api/v1/File/Upload',
  Refresh_Token_Path: '/api/Token/Refresh',
  SignalR: '/ssignalr',
  SignalR2: '/signalR',
};
